/* ============================================================
   OBSEDIAN — APP LOGIC
   app.js — Reads from data.js and renders all dynamic content.
   DO NOT edit this file to update pricing or portfolio.
   Edit data.js instead.
   ============================================================ */

(function () {
  "use strict";

  // ── Guard: ensure data.js loaded correctly ───────────────
  if (typeof OBSEDIAN_DATA === "undefined") {
    console.error("OBSEDIAN: data.js failed to load. Check that it is included before app.js in index.html.");
    return;
  }

  const D = OBSEDIAN_DATA;

  // ── Colour map: service ID → CSS variable value ──────────
  const SERVICE_COLORS = {};
  D.services.forEach((s) => { SERVICE_COLORS[s.id] = s.accentColor; });

  // ────────────────────────────────────────────────────────
  //  HELPER UTILITIES
  // ────────────────────────────────────────────────────────

  /** Safely get element by ID. Logs warning if not found. */
  function el(id) {
    const node = document.getElementById(id);
    if (!node) console.warn(`OBSEDIAN: element #${id} not found.`);
    return node;
  }

  /** Inject HTML string into element. Returns early if element missing. */
  function inject(id, html) {
    const node = el(id);
    if (node) node.innerHTML = html;
  }

  /** Append HTML to element. */
  function append(id, html) {
    const node = el(id);
    if (node) node.insertAdjacentHTML("beforeend", html);
  }

  // ────────────────────────────────────────────────────────
  //  TICKER TAPE
  // ────────────────────────────────────────────────────────
  function buildTicker() {
    const items = D.services.map((s) => `<span class="ticker-item">${s.title}</span>`).join("");
    // Duplicate for seamless loop
    inject("tickerTrack", items + items + items + items);
  }

  // ────────────────────────────────────────────────────────
  //  STATS BAR
  // ────────────────────────────────────────────────────────
  function buildStats() {
    const html = D.stats
      .map(
        (s) => `
      <div class="stat-item reveal">
        <div class="stat-number">${s.number}</div>
        <div class="stat-label">${s.label}</div>
      </div>`
      )
      .join("");
    inject("statsGrid", html);
  }

  // ────────────────────────────────────────────────────────
  //  SERVICES GRID
  // ────────────────────────────────────────────────────────
  function buildServices() {
    const html = D.services
      .map(
        (s, i) => `
      <div class="service-card reveal" style="--card-accent: ${s.accentColor}">
        <span class="service-number">0${i + 1}</span>
        <span class="service-icon">${s.icon}</span>
        <h3 class="service-title">${s.title}</h3>
        <div class="service-subtitle">${s.subtitle}</div>
        <p class="service-desc">${s.description}</p>
        <ul class="service-bullets">
          ${s.bullets.map((b) => `<li class="service-bullet">${b}</li>`).join("")}
        </ul>
      </div>`
      )
      .join("");
    inject("servicesGrid", html);
  }

  // ────────────────────────────────────────────────────────
  //  PRICING CARDS
  // ────────────────────────────────────────────────────────
  function buildPricing() {
    const html = D.pricing
      .map((pkg) => {
        const color = SERVICE_COLORS[pkg.serviceId] || "#FFE000";
        const badge = pkg.badgeVisible
          ? `<div class="pricing-badge" style="background:${color};">${pkg.badge}</div>`
          : "";
        const includes = pkg.includes
          .map((item) => `<li class="pricing-include-item">${item}</li>`)
          .join("");

        return `
        <div class="pricing-card reveal" style="--card-accent: ${color}">
          ${badge}
          <div class="pricing-name">${pkg.packageName}</div>
          <div class="pricing-price">${pkg.price}</div>
          <div class="pricing-note-sm">${pkg.priceNote}</div>
          <hr class="pricing-divider" />
          <ul class="pricing-includes">${includes}</ul>
          <a href="#contact" class="btn btn-primary"
             onclick="prefillService('${pkg.serviceId}')">${pkg.cta}</a>
        </div>`;
      })
      .join("");
    inject("pricingGrid", html);
  }

  // Prefill the contact form service dropdown when clicking pricing CTA
  window.prefillService = function (serviceId) {
    const select = el("fservice");
    if (select) {
      select.value = serviceId;
      // Small delay to allow scroll to complete before flash
      setTimeout(() => {
        select.style.boxShadow = "0 0 0 4px var(--yellow)";
        setTimeout(() => { select.style.boxShadow = ""; }, 1200);
      }, 600);
    }
  };

  // ────────────────────────────────────────────────────────
  //  CONTACT SECTION (info + social + form)
  // ────────────────────────────────────────────────────────
  function buildContact() {
    // Info items
    const infoHtml = `
      <div class="contact-info-item">
        <div class="contact-info-icon">✉</div>
        <a href="mailto:${D.agency.email}">${D.agency.email}</a>
      </div>
      <div class="contact-info-item">
        <div class="contact-info-icon">📞</div>
        <a href="tel:${D.agency.phone}">${D.agency.phone}</a>
      </div>
      <div class="contact-info-item">
        <div class="contact-info-icon">📍</div>
        <span>${D.agency.location}</span>
      </div>`;
    inject("contactInfo", infoHtml);

    // Social links
    const socialHtml = Object.entries(D.agency.socialLinks)
      .map(([name, url]) => `<a class="social-link" href="${url}" target="_blank" rel="noopener">${name.toUpperCase()}</a>`)
      .join("");
    inject("contactSocial", socialHtml);

    // Set Formspree endpoint
    const form = el("contactForm");
    if (form) form.setAttribute("action", D.agency.formspreeEndpoint);

    // Populate service dropdown
    const select = el("fservice");
    if (select) {
      D.services.forEach((s) => {
        const opt = document.createElement("option");
        opt.value = s.id;
        opt.textContent = s.title;
        select.appendChild(opt);
      });
    }
  }

  // ────────────────────────────────────────────────────────
  //  CONTACT FORM SUBMISSION (AJAX — no page reload)
  // ────────────────────────────────────────────────────────
  function initContactForm() {
    const form   = el("contactForm");
    const status = el("formStatus");
    const btn    = el("formSubmitBtn");
    if (!form || !status || !btn) return;

    form.addEventListener("submit", async (e) => {
      e.preventDefault();

      const endpoint = form.getAttribute("action");
      if (!endpoint || endpoint.includes("YOUR_ENDPOINT")) {
        status.textContent = "⚠ Formspree endpoint not configured. Update OBSEDIAN_DATA.agency.formspreeEndpoint in data.js.";
        status.className = "form-status error";
        return;
      }

      btn.textContent   = "SENDING... ✈";
      btn.disabled      = true;
      status.className  = "form-status";
      status.textContent = "";

      try {
        const data = new FormData(form);
        const res  = await fetch(endpoint, {
          method:  "POST",
          body:    data,
          headers: { Accept: "application/json" }
        });

        if (res.ok) {
          status.textContent = "🎉 BRIEF RECEIVED! We'll be back within 4 hours.";
          status.className   = "form-status success";
          form.reset();
        } else {
          const json = await res.json().catch(() => ({}));
          const msg  = json?.errors?.[0]?.message || "Submission failed. Please try again.";
          status.textContent = `❌ ${msg}`;
          status.className   = "form-status error";
        }
      } catch {
        status.textContent = "❌ Network error. Please check your connection and try again.";
        status.className   = "form-status error";
      } finally {
        btn.textContent = "LAUNCH THE BRIEF 🚀";
        btn.disabled    = false;
      }
    });
  }

  // ────────────────────────────────────────────────────────
  //  FOOTER YEAR
  // ────────────────────────────────────────────────────────
  function buildFooter() {
    const yearEl = el("footerYear");
    if (yearEl) yearEl.textContent = new Date().getFullYear();
  }

  // ────────────────────────────────────────────────────────
  //  SCROLL REVEAL (IntersectionObserver)
  // ────────────────────────────────────────────────────────
  function observeReveal() {
    const targets = document.querySelectorAll(".reveal:not(.visible), .reveal-pop:not(.visible), .reveal-left:not(.visible)");
    if (!targets.length) return;

    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("visible");
            io.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12 }
    );
    targets.forEach((t) => io.observe(t));
  }

  // ────────────────────────────────────────────────────────
  //  SMOOTH NAV + HEADER SCROLL EFFECT
  // ────────────────────────────────────────────────────────
  function initNav() {
    const header = el("siteHeader");
    window.addEventListener(
      "scroll",
      () => {
        if (!header) return;
        header.style.borderBottomColor = window.scrollY > 20 ? "var(--yellow)" : "var(--black)";
      },
      { passive: true }
    );

    // Close mobile menu when link clicked
    document.querySelectorAll(".mm-link").forEach((link) => {
      link.addEventListener("click", () => closeMobileMenu());
    });
  }

  // ────────────────────────────────────────────────────────
  //  MOBILE MENU TOGGLE
  // ────────────────────────────────────────────────────────
  function initMobileMenu() {
    const btn  = el("navHamburger");
    const menu = el("mobileMenu");
    if (!btn || !menu) return;
    btn.addEventListener("click", () => {
      const isOpen = menu.classList.toggle("open");
      btn.classList.toggle("open", isOpen);
      document.body.style.overflow = isOpen ? "hidden" : "";
    });
  }
  function closeMobileMenu() {
    const btn  = el("navHamburger");
    const menu = el("mobileMenu");
    if (!menu) return;
    menu.classList.remove("open");
    btn?.classList.remove("open");
    document.body.style.overflow = "";
  }

  // ────────────────────────────────────────────────────────
  //  CUSTOM CURSOR
  // ────────────────────────────────────────────────────────
  function initCursor() {
    const dot  = el("cursorDot");
    const ring = el("cursorRing");
    if (!dot || !ring) return;

    let ringX = 0, ringY = 0;
    let dotX  = 0, dotY  = 0;

    document.addEventListener("mousemove", (e) => {
      dotX = e.clientX; dotY = e.clientY;
      dot.style.left  = dotX + "px";
      dot.style.top   = dotY + "px";
    }, { passive: true });

    (function animateRing() {
      ringX += (dotX - ringX) * 0.15;
      ringY += (dotY - ringY) * 0.15;
      ring.style.left = ringX + "px";
      ring.style.top  = ringY + "px";
      requestAnimationFrame(animateRing);
    })();

    document.addEventListener("mouseleave", () => { dot.style.opacity = "0"; ring.style.opacity = "0"; });
    document.addEventListener("mouseenter", () => { dot.style.opacity = "1"; ring.style.opacity = "1"; });
  }

  // ────────────────────────────────────────────────────────
  //  ACTIVE NAV LINK ON SCROLL (highlight current section)
  // ────────────────────────────────────────────────────────
  function initActiveNav() {
    const sections = document.querySelectorAll("section[id]");
    const navLinks = document.querySelectorAll(".nav-links a[href^='#']");

    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (!entry.isIntersecting) return;
          const id = entry.target.getAttribute("id");
          navLinks.forEach((link) => {
            const active = link.getAttribute("href") === `#${id}`;
            link.style.color = active ? "var(--yellow)" : "";
          });
        });
      },
      { rootMargin: "-40% 0px -55% 0px" }
    );
    sections.forEach((s) => io.observe(s));
  }

  // ────────────────────────────────────────────────────────
  //  INIT — render everything in order
  // ────────────────────────────────────────────────────────
  function init() {
    buildTicker();
    buildStats();
    buildServices();
    buildPricing();
    buildContact();
    buildFooter();
    initContactForm();
    initNav();
    initMobileMenu();
    initCursor();
    initActiveNav();

    // Trigger initial reveal pass after short frame delay
    // (ensures elements are in DOM before observing)
    requestAnimationFrame(() => {
      requestAnimationFrame(observeReveal);
    });
  }

  // Run on DOMContentLoaded
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
